# Generated by Django 4.2.21 on 2025-06-04 17:19

from django.db import migrations, models
import django.db.models.deletion

def create_categories(apps, schema_editor):
    Category = apps.get_model('ecofinds', 'Category')
    Product = apps.get_model('ecofinds', 'Product')
    
    # Get all unique category names from products
    category_names = Product.objects.values_list('category', flat=True).distinct()
    
    # Create Category objects for each unique category name
    for name in category_names:
        Category.objects.get_or_create(name=name)

def convert_categories_to_objects(apps, schema_editor):
    Product = apps.get_model('ecofinds', 'Product')
    Category = apps.get_model('ecofinds', 'Category')
    
    # Update products to use Category objects
    for product in Product.objects.all():
        category = Category.objects.get(name=product.category)
        product.category_id = category.id
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ecofinds', '0002_supportticket_rename_pincode_userprofile_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunPython(create_categories),
        migrations.AddField(
            model_name='product',
            name='category_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecofinds.category'),
        ),
        migrations.RunPython(convert_categories_to_objects),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecofinds.category'),
        ),
    ]
