# Generated by Django 4.2.21 on 2025-06-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecofinds', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
