# Generated by Django 4.2.21 on 2025-06-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecofinds', '0005_remove_product_name_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('used', 'Acceptable')], default='good', max_length=4),
        ),
    ]
