# Generated by Django 4.2.21 on 2025-06-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_remove_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('auction', 'Auction')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('used', 'Acceptable')], default='new', max_length=20),
        ),
    ]
