# Generated by Django 4.2.21 on 2025-06-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_latitude_remove_product_longitude_remove_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('used', 'Acceptable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(help_text='Enter your city', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
