# Generated by Django 4.2.21 on 2025-06-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='average_seller_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_seller_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
